[package]
name = "coordinates"
version = "0.2.0"
authors = ["Mattis Marjak <mattis.marjak@gmail.com>"]
license = "MIT"

[dependencies]
lazy_static = "*"
rustc-serialize = { version = "*", optional = true}
